### ISSUE TITLE
projectors in exponentials

### ISSUE THREAD

**Issue by MeerKatDev** [bernie-wu/BernDirac#2]
FIrst of all, thanks a lot for the package. It seems to work very well and it's really simple to use.

I think the template is too much :) , so I will just freely write all the necessary info:

I'm on Mathematica 12.2 on MacOS Big Sur, and I'm trying to simplify a procedure I have to compute by hand every time. For the simplest parts it works well, for example
```mathematica
1/Sqrt[2] Sum[Exp[I i \[Phi][0]] Ket[i], {i, 0, s}]
```
gives correctly
```mathematica
{{1/Sqrt[2]}, {1/Sqrt[2]}}
``` 
as calculated by hand. But when I put a projector in an exponential:
```mathematica
Exp[I Pi Ket[1] . Bra[1] ]
```
it gives
```mathematica
{{1, 1}, {1, -1}}
```
where I think it's supposed to give 
```mathematica
{{1, 0}, {0, -1}}
```
because it reduces to an `Id[2x2] - 2|1><1|`, so there should be zeros in the nondiagonal places.

**Comment by bernwo** [comment]
Hi @MeerKatDev, in Mathematica, you have to use `MatrixExp[]` instead of `Exp[]` when dealing with matrix exponentials.

Hope that solves the problem :)

Best,
-Bernard

**Comment by MeerKatDev** [comment]
thanks!!
